### ISSUE TITLE
Not compatible with the current version

### ISSUE THREAD

**Issue by ceoshikhar** [anuragsoni/paper-theme#1]
<img width="575" alt="Screenshot 2022-02-17 at 2 39 13 PM" src="https://user-images.githubusercontent.com/62669971/154442774-88774392-5b7d-41c9-8a9f-ae2ddf4e45a2.png">

I use this theme in my NeoVim setup and I am really looking forward to using this with my VSCode setup too.

Thanks!

**Comment by anuragsoni** [comment]
I've updated the extension to relax the lower bound of the vscode engine version. The new version number is 0.3.3 and it should work with the vsode version you are using. Re-open this issue if you are still unable to install the extension.
